title:             yeomi's Blog
email:             hsyeom92@gmail.com
description:       Blog of developer
author:            Yeom Hyeseon
baseurl:           "/"
url:               "http://yeomi92.github.io"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   yeomi92
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
